.TH YLLW 1 "JUNE 2022" "Linux" "User Manuals"
.SH NAME
.B yllw\fR \- A suckless X11 blue light filter in less then 100 lines of C.

.SH SYNOPSIS
\fByllw\fR [\fB\-r\fR \fIn\fR] [\fB\-g\fR \fIn\fR] [\fB\-b\fR \fIn\fR] [\fB\-a\fR \fIn\fR]


.SH DESCRIPTION
\fByllw\fR is basically a configurable color overlay for X11. You can configure the
red, green, blue, and opacity settings of the overlay. Each \fIn\fR value is a floating
point number (double percision), and must be between 0.0 and 1.0.

.SH OPTIONS
.TP
.BI \-r " n"
Set the red channel to \fIn\fR.

.TP
.BI \-g " n"
Set the green channel to \fIn\fR.

.TP
.BI \-b " n"
Set the red channel to \fIn\fR.

.TP
.BI \-a " n"
Set the opacity channel to \fIn\fR.

.SH AUTHOR
dosisod <https://github.com/dosisod>
